<?php

/*******************************************************************************
*   Load Theme Options
*  @package HawkTheme
*  @since Mondeo 1.0
*******************************************************************************/

$options = array (

	//Global
	array( "type" => "box", "num" => "1"),

	array( "name" => "Custom Favicon",
				"desc" => "Set your site favicon, you can upload a image. ",
				"type" => "info",
			 ),

			 array( "name" => "Favicon Image",
						"desc" => "Enter the full URL location of your custom favicon which is visible in browser favorites and tabs.<b>(Must be .png or .ico file - 16px by 16px ).</b>",
						"id" => $shortname."_favicon_image",
						"std" => "",
						"type" => "upload",
					 ),

	 array( "name" => "Email Address",
				"desc" => "The email will use for getting the letter form contact form. ",
				"type" => "info",
				 ),

			  array( "name" => "Email",
						"desc" => "Enter your email address for contact form. <br />Ex: yourname@gmail.com",
						"id" => $shortname."_email",
						"std" => get_option('admin_email'),
						"class" => "ht-section-longtext",
						"type" => "text",
					 ),

	array( "name" => "Custom Code",
				"desc" => "Any code you add here will appear in the head section of every page of your site.",
				"type" => "info",
				 ),

			 array( "name" => "Custom CSS",
						"desc" => "Add only the css code without &lt;style&gt;&lt;/style&gt; style blocks. They are auto added.",
						"id" => $shortname."_custom_css",
						"std" => "",
						"type" => "textarea",
					 ),

			 array( "name" => "Custom Script",
						"desc" => "Any code you add here will appear in the head section, just before &lt;/head&gt; of every page of your site.",
						"id" => $shortname."_custom_script",
						"std" => "",
						"type" => "textarea",
					 ),

	array( "type" => "boxend"),

	//Fonts
	array( "type" => "box", "num" => "2"),

	array( "name" => "Font Family",
				"desc" => "Choose a font family type for your site.",
				"type" => "info",
			 ),

		 array("name" => "Body Font",
						"desc" => "Use this option to change the body family for your site.",
						"id" => $shortname."_body_font_family",
						"std" => "droid-sans",
						"options" => $body_font_family,
						"custom" => "body_font",
						"type" => "select_value",
					 ),

		 array("name" => "Headers Font",
					"desc" => "Use this option to change the headers family for your site. <br />Note:Give a second for each Google font to load when previewing.",
					"id" => $shortname."_headers_font_family",
					"std" => "Yanone+Kaffeesatz",
					"options" => $headers_font_family,
					"custom" => "header_font",
					"type" => "select_value",
				 ),

	array( "name" => "Font Size",
				"desc" => "Set your site font size. Such as logo text size, logo description size, top level menu text size, body font size, hgroup font size.",
				"type" => "info",
			 ),

		 array( "name" => "Logo Text",
					"desc" => "Set your logo text size, the font size is pixels.",
					"id" => $shortname."_logo_text_size",
					"std" => "36",
					"min" => "1",
					"max" => "60",
					"unit" => "px",
					"type" => "range",
				 ),

		array( "name" => "Logo Description",
					"desc" => "Set your logo description size, the font size is pixels.",
					"id" => $shortname."_logo_description_size",
					"std" => "12",
					"min" => "1",
					"max" => "60",
					"unit" => "px",
					"type" => "range",
				 ),

		array( "name" => "Top Level Menu Text",
					"desc" => "Set your top level menu text  size, the font size is pixels.",
					"id" => $shortname."_top_level_menu_size",
					"std" => "12",
					"min" => "1",
					"max" => "60",
					"unit" => "px",
					"type" => "range",
				 ),

		array( "name" => "Sub Level Menu Text",
					"desc" => "Set your sub level menu text  size, the font size is pixels.",
					"id" => $shortname."_sub_level_menu_size",
					"std" => "12",
					"min" => "1",
					"max" => "60",
					"unit" => "px",
					"type" => "range",
				 ),

		array( "name" => "Page Text",
					"desc" => "Set your page text size, the font size is pixels.",
					"id" => $shortname."_page_text_size",
					"std" => "12",
					"min" => "1",
					"max" => "60",
					"unit" => "px",
					"type" => "range",
				 ),

		array( "name" => "H1",
					"desc" => "Set your h1 size in page text, the font size is pixels.",
					"id" => $shortname."_h1_size",
					"std" => "30",
					"min" => "1",
					"max" => "60",
					"unit" => "px",
					"type" => "range",
				 ),

		array( "name" => "H2",
					"desc" => "Set your h2 size in page text, the font size is pixels.",
					"id" => $shortname."_h2_size",
					"std" => "24",
					"min" => "1",
					"max" => "60",
					"unit" => "px",
					"type" => "range",
				 ),

		array( "name" => "H3",
					"desc" => "Set your h3 size in page text, the font size is pixels.",
					"id" => $shortname."_h3_size",
					"std" => "18",
					"min" => "1",
					"max" => "60",
					"unit" => "px",
					"type" => "range",
				 ),

		array( "name" => "H4",
					"desc" => "Set your h4 size in page text, the font size is pixels.",
					"id" => $shortname."_h4_size",
					"std" => "16",
					"min" => "1",
					"max" => "60",
					"unit" => "px",
					"type" => "range",
				 ),

		array( "name" => "H5",
					"desc" => "Set your h5 size in page text, the font size is pixels.",
					"id" => $shortname."_h5_size",
					"std" => "14",
					"min" => "1",
					"max" => "60",
					"unit" => "px",
					"type" => "range",
				 ),

		array( "name" => "H6",
					"desc" => "Set your h6 size in page text, the font size is pixels.",
					"id" => $shortname."_h6_size",
					"std" => "12",
					"min" => "1",
					"max" => "60",
					"unit" => "px",
					"type" => "range",
				 ),

		array( "name" => "Sidebar Widget Title",
					"desc" => "Set your sidebar widget title size in page text, the font size is pixels.",
					"id" => $shortname."_sidebar_widget_title_size",
					"std" => "18",
					"min" => "1",
					"max" => "60",
					"unit" => "px",
					"type" => "range",
				 ),

		array( "name" => "Footer Widget Title",
					"desc" => "Set your footer widget title size in page text, the font size is pixels.",
					"id" => $shortname."_footer_widget_title_size",
					"std" => "18",
					"min" => "1",
					"max" => "60",
					"unit" => "px",
					"type" => "range",
				 ),

		array( "name" => "Footer Text",
					"desc" => "Set your footer text size in page text, the font size is pixels.",
					"id" => $shortname."_footer_text_size",
					"std" => "11",
					"min" => "1",
					"max" => "60",
					"unit" => "px",
					"type" => "range",
				 ),

	array( "type" => "boxend"),

	//Style
	array( "type" => "box", "num" => "3"),

	array( "name" => "Style Option",
				"desc" => "Select the style to change your site display face.",
				"type" => "info",
				 ),

			 array( "name" => "Style List",
						"desc" => "The default style is deepblue, your can change it which you like.",
						"id" => $shortname."_site_style",
						"std" => "deepblue",
						"type" => "image_selcet",
						"options" => $style_option,
					 ),

	array( "name" => "Custom Background",
				"desc" => "Select the background underline to change your site.",
				"type" => "info",
				 ),

			 array( "name" => "Background List",
						"desc" => "The default background is none, your can change it which you like.",
						"id" => $shortname."_site_background",
						"std" => "none",
						"type" => "image_selcet",
						"options" => $background_option,
					 ),

	array( "name" => "Font Color",
				"desc" => "Change the color of the font.",
				"type" => "info",
				 ),

			array( "name" => "A Link Hex Code",
						"desc" => "Use this option to quickly change the color of the link.",
						"id" => $shortname."_alink_color",
						"std" => "",
						"type" => "color",
					 ),

			array( "name" => "A Link Hover Hex Code",
						"desc" => "Use this option to quickly change the color of the link.",
						"id" => $shortname."_alink_hover_color",
						"std" => "",
						"type" => "color",
					 ),

			array( "name" => "Menu Link Hex Code",
						"desc" => "Use this option to quickly change the color of the link.",
						"id" => $shortname."_menu_color",
						"std" => "",
						"type" => "color",
					 ),

			array( "name" => "Menu Link Hover Hex Code",
						"desc" => "Use this option to quickly change the color of the link.",
						"id" => $shortname."_menu_hover_color",
						"std" => "",
						"type" => "color",
					 ),

			array( "name" => "Body Font Hex Code",
						"desc" => "Use this option to quickly change the color of the link.",
						"id" => $shortname."_body_font_color",
						"std" => "",
						"type" => "color",
					 ),

			array( "name" => "Hgroup Font Hex Code",
						"desc" => "Use this option to quickly change the color of the link.",
						"id" => $shortname."_hgroup_font_color",
						"std" => "",
						"type" => "color",
					 ),

	array( "type" => "boxend"),

	//Header
	array( "type" => "box", "num" => "4"),

	array( "name" => "Header Layout",
				"desc" => "Select a layout mode for your site header.",
				"type" => "info",
			 ),

			 array("name" => "Layout Type",
						"desc" => "Use this option to change the header type mode for your site.",
						"id" => $shortname."_header_type",
						"std" => "Style One",
						"options" => $header_type,
						"type" => "select",
					 ),

	array( "name" => "Custom Logo",
				"desc" => "Set your site logo, you can upload a image. ",
				"type" => "info",
			 ),

			array( "name" => "Upload custom logo",
						"desc" => "Optional way to replace heading and description text for your website with an image.",
						"id" => $shortname."_site_logo",
						"std" => "",
						"type" => "upload",
					 ),

			array( "name" => "Margin Top",
						"desc" => "Set your logo top margin, the size is pixels.",
						"id" => $shortname."_logo_top_margin",
						"std" => "25",
						"min" => "0",
						"max" => "100",
						"unit" => "px",
						"type" => "range",
					 ),

			array( "name" => "Margin Left",
						"desc" => "Set your logo left margin, the size is pixels.",
						"id" => $shortname."_logo_left_margin",
						"std" => "0",
						"min" => "0",
						"max" => "100",
						"unit" => "px",
						"type" => "range",
					 ),

			array( "name" => "Margin Bottom",
						"desc" => "Set your logo bottom margin, the size is pixels.",
						"id" => $shortname."_logo_bottom_margin",
						"std" => "15",
						"min" => "0",
						"max" => "100",
						"unit" => "px",
						"type" => "range",
					 ),

	array( "name" => "Social Media",
				"desc" => "Set the social media button. To select that you want to display, if you don't want to display which one, let it blank.",
				"type" => "info",
			 ),

			 array( "name" => "MySpace",
						"desc" => "This places your myspace link on the site. Leave blank if you want to hide or not use.",
						"id" => $shortname."_topmedia_myspace",
						"std" => '',
						"class" => "ht-section-longtext",
						"type" => "text",
					 ),

			 array( "name" => "Stumble",
						"desc" => "This places your stumble link on the site. Leave blank if you want to hide or not use.",
						"id" => $shortname."_topmedia_stumble",
						"std" => '',
						"class" => "ht-section-longtext",
						"type" => "text",
					 ),

			 array( "name" => "Linkedin",
						"desc" => "This places your linkedin link on the site. Leave blank if you want to hide or not use.",
						"id" => $shortname."_topmedia_linkedin",
						"std" => '',
						"class" => "ht-section-longtext",
						"type" => "text",
					 ),

			array( "name" => "Delicious",
						"desc" => "This places your delicious link on the site. Leave blank if you want to hide or not use.",
						"id" => $shortname."_topmedia_delicious",
						"std" => '',
						"class" => "ht-section-longtext",
						"type" => "text",
					 ),

			array( "name" => "RSS Feed",
						"desc" => "This places your rss link on the site. Leave blank if you want to hide or not use.",
						"id" => $shortname."_topmedia_rss",
						"std" => '',
						"class" => "ht-section-longtext",
						"type" => "text",
					 ),

			array( "name" => "Digg",
						"desc" => "This places your digg link on the site. Leave blank if you want to hide or not use.",
						"id" => $shortname."_topmedia_digg",
						"std" => '',
						"class" => "ht-section-longtext",
						"type" => "text",
					 ),

			array( "name" => "FaceBook",
						"desc" => "This places your facebook link on the site. Leave blank if you want to hide or not use.",
						"id" => $shortname."_topmedia_facebook",
						"std" => '',
						"class" => "ht-section-longtext",
						"type" => "text",
					 ),

			array( "name" => "Flickr",
						"desc" => "This places your flickr link on the site. Leave blank if you want to hide or not use.",
						"id" => $shortname."_topmedia_flickr",
						"std" => '',
						"class" => "ht-section-longtext",
						"type" => "text",
					 ),

			array( "name" => "Twitter",
						"desc" => "This places your twitter link on the site. Leave blank if you want to hide or not use.",
						"id" => $shortname."_topmedia_twitter",
						"std" => '',
						"class" => "ht-section-longtext",
						"type" => "text",
					 ),


			 array( "name" => "Gtalk",
						"desc" => "This places your gtalk link on the site. Leave blank if you want to hide or not use.",
						"id" => $shortname."_topmedia_gtalk",
						"std" => '',
						"class" => "ht-section-longtext",
						"type" => "text",
					 ),

	array( "type" => "boxend"),


	//Homepage
	array( "type" => "box", "num" => "5"),

	array( "name" => "Homepage Content Editor",
				"desc" => "The text you enter here will display on the homepage.",
				"type" => "info",
			 ),

			 array( "name" => "",
						"desc" => "The text you enter here will display on the homepage, you can enter any text or shortcode to this editor.",
						"id" => $shortname."_shortcode_content",
						"std" => "",
						"type" => "editor",
					 ),

	array( "name" => "Slogan",
				"desc" => "Here you can determine what the homepage slogan says or leave it blank in order to hide it all together.",
				"type" => "info",
			 ),

			 array("name" => "Enabled or Disabled Slogan",
						"desc" => "Click the button to turn on or off the slogan, this will set the slogan enabled or disabled on homepage.",
						"id" => $shortname."_slogan_display",
						"std" => "true",
						"type" => "on_off",
					 ),

			 array( "name" => "Slogan Title",
						"desc" => "Leave the slogan title blank if you don't want it to show.",
						"id" => $shortname."_slogan_title",
						"std" => 'This your slogan title. Change it or hide it.',
						"class" => "ht-section-longtext",
						"type" => "text",
					 ),

			array( "name" => "Slogan Text",
						"desc" => "Leave the slogan text blank if you don't want it to show.",
						"id" => $shortname."_slogan_text",
						"std" => "This your slogan text. You can change it or hide it. If you don't want it to show, you can leve it blank.",
						"type" => "textarea",
					 ),

			array( "name" => "Slogan Button Text",
						"desc" => "Leave the slogan button text blank if you don't want it to show.",
						"id" => $shortname."_slogan_botton_text",
						"std" => '',
						"class" => "ht-section-shorttext",
						"type" => "text",
					 ),

			 array( "name" => "Slogan Button Link",
						"desc" => "Leave the slogan button link blank if you don't want it to show.",
						"id" => $shortname."_slogan_botton_link",
						"std" => '',
						"class" => "ht-section-longtext",
						"type" => "text",
					 ),

	array( "type" => "boxend"),


	//Slides
	array( "type" => "box", "num" => "6"),

	array( "name" => "Slide Display",
				"desc" => "Enabled or disabled the slide.",
				"type" => "info",
			 ),

			  array("name" => "Enabled or Disabled Slide",
						"desc" => "Click the button to turn on or off the slide, this will set the slide enabled or disabled on homepage.",
						"id" => $shortname."_slide_display",
						"std" => "true",
						"type" => "on_off",
					 ),

	array( "name" => "Slide Type Select",
				"desc" => "Choose a slide type for your slideshow.",
				"type" => "info",
			 ),

			 array("name" => "Slide Type",
						"desc" => "Use this option to change the slide type mode on homepage.",
						"id" => $shortname."_slide_type",
						"std" => "Nivo Slider",
						"options" => $slide_type,
						"type" => "select",
					 ),

	array( "name" => "Slide Category",
				"desc" => "Choose the category for your slideshow.",
				"type" => "info",
			 ),

			  array("name" => "Category",
						"desc" => "Use this option to change the slide category.",
						"id" => $shortname."_slide_terms",
						"std" => "",
						"tax" => "slider",
						"type" => "terms",
					 ),

			array("name" => "Multiple Category",
						"desc" => "If you want to display more category, you can enter the name of category here. Separate categories with commas.<b> Ex: Answers, News</b>",
						"id" => $shortname."_slide_multiple_terms",
						"std" => "",
						"class" => "ht-section-longtext",
						"type" => "text",
					 ),

	array( "name" => "ShowPosts",
				"desc" => "Select the number for the slider posts. It just use for nivo slider and piecemaker slider.",
				"type" => "info",
			 ),

			array( "name" => "Posts",
						"desc" => "Select the number for the slider posts. <br /><b>It just use for nivo slider and piecemaker slider.</b>",
						"id" => $shortname."_slide_showposts",
						"std" => "3",
						"min" => "1",
						"unit" => "posts",
						"max" => "20",
						"type" => "range",
					 ),

	array( "name" => "Nivo Slider Settings",
				"desc" => "Set the effect, speed, and delay for your nivo slider. This just use for nivo slider.",
				"type" => "info",
			 ),

			  array("name" => "Effect",
						"desc" => "Use this option to change the slide effect mode.",
						"id" => $shortname."_slide_nivo_effect",
						"std" => "random",
						"options" => $slide_nivo_effect,
						"type" => "select",
					 ),

			 array( "name" => "Speed",
						"desc" => "Select the number for the slider speed. The unit is millisecond.",
						"id" => $shortname."_slide_nivo_speed",
						"std" => "500",
						"min" => "100",
						"max" => "3000",
						"unit" => "millisecond",
 						"type" => "range",
					 ),

			 array( "name" => "Delay",
						"desc" => "Select the number for the slider delay. The unit is millisecond.",
						"id" => $shortname."_slide_nivo_delay",
						"std" => "5000",
						"min" => "500",
						"max" => "20000",
						"unit" => "millisecond",
 						"type" => "range",
					 ),

	array( "name" => "Piecemaker Slider Settings",
				"desc" => "Set the effect, and delay for your piecemaker slider. This just use for piecemaker slider.",
				"type" => "info",
			 ),

			  array("name" => "Effect",
						"desc" => "Use this option to change the slide effect mode.",
						"id" => $shortname."_slide_piecemaker_effect",
						"std" => "easeInOutCubic",
						"options" => $slide_piecemaker_effect,
						"type" => "select",
					 ),

			 array( "name" => "Delay",
						"desc" => "Select the number for the slider delay. The unit is second.",
						"id" => $shortname."_slide_piecemaker_delay",
						"std" => "5",
						"min" => "0",
						"max" => "50",
						"unit" => "second",
 						"type" => "range",
					 ),

	array( "name" => "Kwicks Slider Settings",
				"desc" => "Set the speed for your kwicks slider. This just use for nivo slider.",
				"type" => "info",
			 ),

			 array( "name" => "Speed",
						"desc" => "Select the number for the slider speed. The unit is millisecond.",
						"id" => $shortname."_slide_kwicks_speed",
						"std" => "300",
						"min" => "100",
						"max" => "3000",
						"unit" => "millisecond",
 						"type" => "range",
					 ),

	array( "name" => "Roundabout Slider Settings",
				"desc" => "Set the speed and delay for your roundabout slider. This just use for roundabout slider.",
				"type" => "info",
			 ),

			 array("name" => "Effect",
						"desc" => "Use this option to change the slide effect mode.",
						"id" => $shortname."_slide_roundabout_effect",
						"std" => "easeInOutBack",
						"options" => $slide_roundabout_effect,
						"type" => "select",
					 ),

			 array( "name" => "Speed",
						"desc" => "Select the number for the slider speed. The unit is millisecond.",
						"id" => $shortname."_slide_roundabout_speed",
						"std" => "2000",
						"min" => "100",
						"max" => "10000",
						"unit" => "millisecond",
 						"type" => "range",
					 ),

			array( "name" => "Delay",
						"desc" => "Select the number for the slider delay. The unit is millisecond.",
						"id" => $shortname."_slide_roundabout_delay",
						"std" => "3000",
						"min" => "100",
						"max" => "10000",
						"unit" => "millisecond",
 						"type" => "range",
					 ),

	array( "type" => "boxend"),

	//Portfolio
	array( "type" => "box", "num" => "7"),

	array( "name" => "ShowPosts",
				"desc" => "Select the number for the portfolio posts. It just use for portfolio page lists.",
				"type" => "info",
			 ),

			array( "name" => "Posts",
						"desc" => "Select the number for the portfolio posts. <br /><b>It just use for portfolio page lists.</b>",
						"id" => $shortname."_portfolio_showposts",
						"std" => "12",
						"min" => "1",
						"unit" => "posts",
						"max" => "64",
						"type" => "range",
					 ),

	array( "name" => "Post Byline Information",
				"desc" => "What should be shown in post bylines?",
				"type" => "info",
			 ),

			  array( "type" => "checktop"),

			  array( "name" => "Author",
						"id" => $shortname."_portfolio_post_byline_author",
						"std" => "true",
						"type" => "checkbox",
					 ),

			 array( "name" => "Date",
						"id" => $shortname."_portfolio_post_byline_date",
						"std" => "true",
						"type" => "checkbox",
					 ),

			 array( "name" => "Comments",
						"id" => $shortname."_portfolio_post_byline_comments",
						"std" => "true",
						"type" => "checkbox",
					 ),

			 array( "name" => "Categories",
						"id" => $shortname."_portfolio_post_byline_categories",
						"std" => "true",
						"type" => "checkbox",
					 ),

			 array( "type" => "checkbottom",
						"desc" => "The byline shows meta information about who wrote the post, what category it is in, etc... Use this option to control what is shown.",
					 ),

	array( "name" => "Portfolio Layout Mode",
				"desc" => "Select your default layout mode, this can be changed on individual pages.Once selected, you can adjust the layout in the Layout Builder.",
				"type" => "info",
			 ),

			 array( "name" => "List Page Layout",
						"desc" => "The default layout for your site of portfolios; the posttype of portfolio list page will always have this layout.",
						"id" => $shortname."_portfolio_layout_lists",
						"std" => "four column",
						"type" => "image_selcet",
						"options" => $portfolio_layout_lists,
					 ),

			 array( "name" => "Single Page Layout",
						"desc" => "The default layout for your site of portfolio; the posttype of post single page will always have this layout.",
						"id" => $shortname."_portfolio_layout_single",
						"std" => "right side",
						"type" => "image_selcet",
						"options" => $page_layout_single,
					 ),

	array( "name" => "About Author Display",
				"desc" => "Enabled or disabled the author info in single post page.",
				"type" => "info",
			 ),

			  array("name" => "Enabled or Disabled",
						"desc" => "Click the button to turn on or off the author info, this will set the author info enabled or disabled on single page of portfolio.",
						"id" => $shortname."_portfolio_author_info_display",
						"std" => "true",
						"type" => "on_off",
					 ),

	array( "type" => "boxend"),

	//Blog
	array( "type" => "box", "num" => "8"),

	array( "name" => "ShowPosts",
				"desc" => "Select the number for the blog posts. It just use for blog page lists.",
				"type" => "info",
			 ),

			array( "name" => "Posts",
						"desc" => "Select the number for the blog posts. <br /><b>It just use for blog page lists.</b>",
						"id" => $shortname."_blog_showposts",
						"std" => "8",
						"min" => "1",
						"unit" => "posts",
						"max" => "64",
						"type" => "range",
					 ),

	array( "name" => "Post Byline Information",
				"desc" => "What should be shown in post bylines?",
				"type" => "info",
			 ),

			  array( "type" => "checktop"),

			  array( "name" => "Author",
						"id" => $shortname."_blog_post_byline_author",
						"std" => "true",
						"type" => "checkbox",
					 ),

			 array( "name" => "Date",
						"id" => $shortname."_blog_post_byline_date",
						"std" => "true",
						"type" => "checkbox",
					 ),

			 array( "name" => "Comments",
						"id" => $shortname."_blog_post_byline_comments",
						"std" => "true",
						"type" => "checkbox",
					 ),

			 array( "name" => "Categories",
						"id" => $shortname."_blog_post_byline_categories",
						"std" => "true",
						"type" => "checkbox",
					 ),

			 array( "type" => "checkbottom",
						"desc" => "The byline shows meta information about who wrote the post, what category it is in, etc... Use this option to control what is shown.",
					 ),

	array( "name" => "Blog Layout Mode",
				"desc" => "Select your default layout mode, this can be changed on individual pages.Once selected, you can adjust the layout in the Layout Builder.",
				"type" => "info",
			 ),

			 array( "name" => "List Page Layout",
						"desc" => "The default layout for your site of blog; the posttype of post list page will always have this layout.",
						"id" => $shortname."_blog_layout_lists",
						"std" => "right side",
						"type" => "image_selcet",
						"options" => $page_layout_lists,
					 ),

			array( "name" => "Single Page Layout",
						"desc" => "The default layout for your site of blog; the posttype of post single page will always have this layout.",
						"id" => $shortname."_blog_layout_single",
						"std" => "right side",
						"type" => "image_selcet",
						"options" => $page_layout_single,
					 ),

	array( "name" => "About Author Display",
				"desc" => "Enabled or disabled the author info in single post page.",
				"type" => "info",
			 ),

			  array("name" => "Enabled or Disabled",
						"desc" => "Click the button to turn on or off the author info, this will set the author info enabled or disabled on single page of blog.",
						"id" => $shortname."_blog_author_info_display",
						"std" => "true",
						"type" => "on_off",
					 ),

	array( "name" => "Related Posts Display",
				"desc" => "Enabled or disabled the related posts, this will set the related posts enabled or disabled on single page of blog.",
				"type" => "info",
			 ),

			  array("name" => "Enabled or Disabled",
						"desc" => "Click the button to turn on or off the related posts, this will set the related posts enabled or disabled on single page of blog.",
						"id" => $shortname."_related_posts_display",
						"std" => "true",
						"type" => "on_off",
					 ),

	array( "type" => "boxend"),

	//News
	array( "type" => "box", "num" => "9"),

	array( "name" => "ShowPosts",
				"desc" => "Select the number for the news posts. It just use for news page lists.",
				"type" => "info",
			 ),

			array( "name" => "Posts",
						"desc" => "Select the number for the news posts. <br /><b>It just use for news page lists.</b>",
						"id" => $shortname."_news_showposts",
						"std" => "8",
						"min" => "1",
						"unit" => "posts",
						"max" => "64",
						"type" => "range",
					 ),

	array( "name" => "Post Byline Information",
				"desc" => "What should be shown in post bylines?",
				"type" => "info",
			 ),

			  array( "type" => "checktop"),

			  array( "name" => "Author",
						"id" => $shortname."_news_post_byline_author",
						"std" => "true",
						"type" => "checkbox",
					 ),

			 array( "name" => "Date",
						"id" => $shortname."_news_post_byline_date",
						"std" => "true",
						"type" => "checkbox",
					 ),

			 array( "name" => "Comments",
						"id" => $shortname."_news_post_byline_comments",
						"std" => "true",
						"type" => "checkbox",
					 ),

			 array( "name" => "Categories",
						"id" => $shortname."_news_post_byline_categories",
						"std" => "true",
						"type" => "checkbox",
					 ),

			 array( "type" => "checkbottom",
						"desc" => "The byline shows meta information about who wrote the post, what category it is in, etc... Use this option to control what is shown.",
					 ),

	array( "name" => "News Layout Mode",
				"desc" => "Select your default layout mode, this can be changed on individual pages.Once selected, you can adjust the layout in the Layout Builder.",
				"type" => "info",
			 ),

			 array( "name" => "List Page Layout",
						"desc" => "The default layout for your site of news; the posttype of post list page will always have this layout.",
						"id" => $shortname."_news_layout_lists",
						"std" => "right side",
						"type" => "image_selcet",
						"options" => $page_layout_lists,
					 ),

			array( "name" => "Single Page Layout",
						"desc" => "The default layout for your site of news; the posttype of post single page will always have this layout.",
						"id" => $shortname."_news_layout_single",
						"std" => "right side",
						"type" => "image_selcet",
						"options" => $page_layout_single,
					 ),

	array( "name" => "About Author Display",
				"desc" => "Enabled or disabled the author info in single post page.",
				"type" => "info",
			 ),

			  array("name" => "Enabled or Disabled",
						"desc" => "Click the button to turn on or off the author info, this will set the author info enabled or disabled on single page of news.",
						"id" => $shortname."_news_author_info_display",
						"std" => "true",
						"type" => "on_off",
					 ),

	array( "type" => "boxend"),

	//Gallery
	array( "type" => "box", "num" => "10"),

	array( "name" => "ShowPosts",
				"desc" => "Select the number for the gallery posts. It just use for gallery page lists.",
				"type" => "info",
			 ),

			array( "name" => "Posts",
						"desc" => "Select the number for the gallery posts. <br /><b>It just use for gallery page lists.</b>",
						"id" => $shortname."_gallery_showposts",
						"std" => "12",
						"min" => "1",
						"unit" => "posts",
						"max" => "64",
						"type" => "range",
					 ),

	array( "name" => "Gallery Layout Mode",
				"desc" => "Select your default layout mode, this can be changed on individual pages.Once selected, you can adjust the layout in the Layout Builder.",
				"type" => "info",
			 ),

			 array( "name" => "List Page Layout",
						"desc" => "The default layout for your site of galleries; the posttype of galleries list page will always have this layout.",
						"id" => $shortname."_gallery_layout_lists",
						"std" => "four column",
						"type" => "image_selcet",
						"options" => $gallery_layout_lists,
					 ),

	array( "name" => "Gallery Single Page Settings",
				"desc" => "Set the speed and delay for your gallery single page settings. This just use for gallery single page.",
				"type" => "info",
			 ),

			 array( "name" => "Speed",
						"desc" => "Select the number for the gallery single page slider speed. The unit is millisecond.",
						"id" => $shortname."_gallery_single_slider_speed",
						"std" => "1500",
						"min" => "100",
						"max" => "10000",
						"unit" => "millisecond",
 						"type" => "range",
					 ),

			array( "name" => "Delay",
						"desc" => "Select the number for the gallery single page slider delay. The unit is millisecond.",
						"id" => $shortname."_gallery_single_slider_delay",
						"std" => "3000",
						"min" => "100",
						"max" => "10000",
						"unit" => "millisecond",
 						"type" => "range",
					 ),

	array( "type" => "boxend"),

	//Footer
	array( "type" => "box", "num" => "11"),

	array( "name" => "Footer Widgets Layout Mode",
				"desc" => "Select your default layout mode, this can be changed on individual pages.Once selected, you can adjust the layout in the Layout Builder.",
				"type" => "info",
			 ),

			 array( "name" => "List Page Layout",
						"desc" => "The default layout for your site of footer widgets; the footer of your site will always have this layout.",
						"id" => $shortname."_footer_widgets_layout_lists",
						"std" => "three column",
						"type" => "image_selcet",
						"options" => $footer_widgets_layout_lists,
					 ),

	array( "name" => "CopyRight",
				"desc" => "Custom your copyright, the will display in footer of site.",
				"type" => "info",
				 ),

			 array( "name" => "Copyright Text",
						"desc" => "Enter the copyright text. You can use html also.",
						"id" => $shortname."_copyright",
						"std" => 'Copyright &copy; <a href="'. home_url( '/' ) . '">' .esc_attr( get_bloginfo('name') ).'</a>, Privacy Statement Terms and Conditions.',
						"type" => "textarea",
					 ),

	array( "name" => "Contact Info 1",
				"desc" => "Eenter the contact info, this will display in footer of site.",
				"type" => "info",
				 ),

			 array( "name" => "Contact Title",
						"desc" => "Enter the title for this contact info. Ex: Corporate",
						"id" => $shortname."_footer_contact_title1",
						"std" => '',
						"class" => "ht-section-longtext",
						"type" => "text",
					 ),

			array( "name" => "Contact Detail",
						"desc" => "Enter the address, email, mobile for this contact info.",
						"id" => $shortname."_footer_contact_detail1",
						"std" => "",
						"type" => "textarea",
					 ),

	array( "name" => "Contact Info 2",
				"desc" => "Eenter the contact info, this will display in footer of site.",
				"type" => "info",
				 ),

			 array( "name" => "Contact Title",
						"desc" => "Enter the title for this contact info. Ex: Corporate",
						"id" => $shortname."_footer_contact_title2",
						"std" => '',
						"class" => "ht-section-longtext",
						"type" => "text",
					 ),

			array( "name" => "Contact Detail",
						"desc" => "Enter the address, email, mobile for this contact info.",
						"id" => $shortname."_footer_contact_detail2",
						"std" => "",
						"type" => "textarea",
					 ),

	array( "name" => "Social Media",
					"desc" => "Set the social media button. To select that you want to display, if you don't want to display which one, let it blank.",
					"type" => "info",
				 ),

			array( "name" => "Shortcode",
					"desc" => "Enter the Social Media shortcode here.",
					"id" => $shortname."_footer_social_media",
					"std" => "",
					"type" => "textarea",
				 ),

	array( "type" => "boxend"),

	//SEO
	array( "type" => "box", "num" => "12"),

	array( "name" => "Home Page SEO Options",
				"desc" => "Set your seo settings for your site, this will add the keywords, description, title tag to your meta.",
				"type" => "info",
				 ),

			 array( "name" => "Meta Keywords",
						"desc" => "Enter a comma-separated list of keywords you'd like to associate with this page.<br /><b>Ex:</b>&lt;meta name='keywords' content='keyword1, keyword2, keyword3' /&gt;",
						"id" => $shortname."_home_meta_keywords",
						"std" => "",
						"type" => "textarea",
					 ),

			 array( "name" => "Meta Description",
						"desc" => "Enter a description you'd like to associate with this page.<br /><b>Ex:</b>&lt;meta name='description' content='This is your SEO description of your site.' /&gt;",
						"id" => $shortname."_home_meta_description",
						"std" => "",
						"type" => "textarea",
					 ),

	array( "name" => "PostType SEO Options",
				"desc" => "Set your page and single seo settings for your site, this will add the keywords, description, title tag to your meta.",
				"type" => "info",
				 ),

				 array("name" => "Enabled or Disabled For Page",
						"desc" => "Click the button to turn on or off, this will set the seo settings enabled or disabled for page.",
						"id" => $shortname."_seo_page",
						"std" => "true",
						"type" => "on_off",
					 ),

			 array("name" => "Enabled or Disabled For Post",
						"desc" => "Click the button to turn on or off, this will set the seo settings enabled or disabled for post.",
						"id" => $shortname."_seo_post",
						"std" => "true",
						"type" => "on_off",
					 ),

			array("name" => "Enabled or Disabled For Portfolio",
						"desc" => "Click the button to turn on or off, this will set the seo settings enabled or disabled for portfolio.",
						"id" => $shortname."_seo_portfolio",
						"std" => "true",
						"type" => "on_off",
					 ),

			 array("name" => "Enabled or Disabled For Slider",
						"desc" => "Click the button to turn on or off, this will set the seo settings enabled or disabled for slider.",
						"id" => $shortname."_seo_slider",
						"std" => "true",
						"type" => "on_off",
					 ),

			 array("name" => "Enabled or Disabled For News",
						"desc" => "Click the button to turn on or off, this will set the seo settings enabled or disabled for news.",
						"id" => $shortname."_seo_news",
						"std" => "true",
						"type" => "on_off",
					 ),

			 array("name" => "Enabled or Disabled For Gallery",
						"desc" => "Click the button to turn on or off, this will set the seo settings enabled or disabled for gallery.",
						"id" => $shortname."_seo_gallery",
						"std" => "true",
						"type" => "on_off",
					 ),

	array( "type" => "boxend")

);

?>